#pragma once

#include <ntddk.h>

/*
 * METHOD_BUFFERED only.
 *
 * This is a PnP-style version of MmioInterruptTest.
 * It must not map MMIO or connect interrupts in DriverEntry.
 * It waits for IRP_MN_START_DEVICE and uses the translated resources supplied
 * by the PnP Manager.
 */

#define IOCTL_PNPIT_GET_ID                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x830, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PNPIT_READ_REG32              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x831, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PNPIT_WRITE_REG32             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x832, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PNPIT_WRITE_CONTROL           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x833, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PNPIT_WAIT_FOR_INTERRUPT      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x834, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PNPIT_GET_INTERRUPT_COUNT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x835, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PNPIT_CANCEL_WAIT             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x836, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define PNPIT_ID_VALUE 0x4d4d494fUL /* "MMIO" */

typedef struct _PNPIT_REG32_REQUEST {
    ULONG Offset;
    ULONG Value;
} PNPIT_REG32_REQUEST, *PPNPIT_REG32_REQUEST;
