#pragma once

#include <ntddk.h>

/*
 * METHOD_BUFFERED unless explicitly marked METHOD_OUT_DIRECT.
 *
 * This driver is the DMA-aware version of PowerPnpMmioTest.
 * v0.1 focuses on common-buffer DMA and MDL/direct-buffer plumbing.
 */

#define IOCTL_DMAPNP_GET_ID                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x850, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_GET_DMA_INFO               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x851, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_READ_REG32                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x852, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_WRITE_REG32                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x853, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_WRITE_CONTROL              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x854, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_WAIT_FOR_INTERRUPT         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x855, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_GET_INTERRUPT_COUNT        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x856, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_CANCEL_PENDING             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x857, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_GET_POWER_STATE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x858, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DMAPNP_COMMON_BUFFER_ROUNDTRIP    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x859, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_MDL_SELF_TEST              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x85a, METHOD_BUFFERED, FILE_ANY_ACCESS)

/*
 * This IOCTL should make the I/O Manager create IRP->MdlAddress for the output
 * buffer. It is a direct-buffer plumbing test, not full packet DMA yet.
 */
#define IOCTL_DMAPNP_DIRECT_BUFFER_FILL         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x85b, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DMAPNP_PACKET_DMA_PLACEHOLDER     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x85c, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_DMAPNP_SCATTER_GATHER_PLACEHOLDER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x85d, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define DMAPNP_ID_VALUE 0x444d4131UL /* "DMA1" */

typedef struct _DMAPNP_REG32_REQUEST {
    ULONG Offset;
    ULONG Value;
} DMAPNP_REG32_REQUEST, *PDMAPNP_REG32_REQUEST;

typedef struct _DMAPNP_POWER_STATE_OUT {
    ULONG Started;
    ULONG Powered;
    ULONG SystemPowerState;
    ULONG DevicePowerState;
} DMAPNP_POWER_STATE_OUT, *PDMAPNP_POWER_STATE_OUT;

typedef struct _DMAPNP_DMA_INFO_OUT {
    ULONG NumberOfMapRegisters;
    ULONG CommonBufferLength;
    ULONG CommonLogicalAddressLow;
    ULONG CommonLogicalAddressHigh;
    ULONG CommonBufferAllocated;
} DMAPNP_DMA_INFO_OUT, *PDMAPNP_DMA_INFO_OUT;

typedef struct _DMAPNP_COMMON_ROUNDTRIP {
    ULONG Length;
    ULONG Pattern;
    ULONG Result;
    ULONG InterruptCount;
    ULONG LogicalAddressLow;
    ULONG LogicalAddressHigh;
} DMAPNP_COMMON_ROUNDTRIP, *PDMAPNP_COMMON_ROUNDTRIP;
