#pragma once

#include <ntddk.h>

/*
 * METHOD_BUFFERED only.
 *
 * This driver is intended for userspace-ntos, not production Windows machines.
 * It assumes the NT personality supplies a fake translated MMIO resource at
 * 0x10000000 and a fake interrupt vector 5.
 */

#define IOCTL_MMIOIT_GET_ID                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x820, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MMIOIT_READ_REG32              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x821, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MMIOIT_WRITE_REG32             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x822, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MMIOIT_WRITE_CONTROL           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x823, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MMIOIT_WAIT_FOR_INTERRUPT      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x824, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MMIOIT_GET_INTERRUPT_COUNT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x825, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MMIOIT_CANCEL_WAIT             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x826, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MMIOIT_DISCONNECT_INTERRUPT    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x827, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MMIOIT_RECONNECT_INTERRUPT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x828, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define MMIOIT_ID_VALUE 0x4d4d494fUL /* "MMIO" */

typedef struct _MMIOIT_REG32_REQUEST {
    ULONG Offset;
    ULONG Value;
} MMIOIT_REG32_REQUEST, *PMMIOIT_REG32_REQUEST;
