#pragma once

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <windows.h>
#endif

#define IOCTL_KMDF_DMA_PING                    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x870, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_DMA_GET_INFO                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x871, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_DMA_READ_REG32              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x872, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_DMA_WRITE_REG32             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x873, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_DMA_COMMON_ROUNDTRIP        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x874, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_DMA_TIMER_TEST              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x875, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_DMA_WORKITEM_TEST           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x876, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_DMA_CANCEL_PENDING          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x877, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_DMA_TRANSACTION_PLACEHOLDER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x878, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define KMDF_DMA_PING_VALUE   0x4b444d41UL /* "KDMA" */
#define KMDF_DMA_ID_VALUE     0x4b444d41UL /* "KDMA" */
#define KMDF_DMA_ALT_ID_VALUE 0x444d4131UL /* "DMA1" */

typedef struct _KMDF_DMA_INFO {
    ULONG Prepared;
    ULONG Powered;
    ULONG HasMmio;
    ULONG MmioLength;

    ULONG CommonBufferLength;
    ULONG CommonLogicalAddressLow;
    ULONG CommonLogicalAddressHigh;
    ULONG DmaMaximumLength;

    ULONG IoctlCount;
    ULONG InterruptCount;
    ULONG DpcCount;
    ULONG TimerCount;
    ULONG WorkItemCount;
    ULONG InterruptEnableCount;
    ULONG InterruptDisableCount;
} KMDF_DMA_INFO, *PKMDF_DMA_INFO;

typedef struct _KMDF_DMA_REG32_REQUEST {
    ULONG Offset;
    ULONG Value;
} KMDF_DMA_REG32_REQUEST, *PKMDF_DMA_REG32_REQUEST;

typedef struct _KMDF_DMA_COMMON_ROUNDTRIP {
    ULONG Length;
    ULONG Pattern;
    ULONG Result;
    ULONG InterruptCount;
    ULONG LogicalAddressLow;
    ULONG LogicalAddressHigh;
} KMDF_DMA_COMMON_ROUNDTRIP, *PKMDF_DMA_COMMON_ROUNDTRIP;
