#pragma once

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <windows.h>
#endif

/*
 * METHOD_BUFFERED only.
 *
 * This header is shared by the KMDF driver and the optional user-mode tester.
 */

#define IOCTL_KMDF_BASIC_PING          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x860, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_BASIC_ECHO          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x861, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_BASIC_GET_VERSION   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x862, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_BASIC_GET_STATE     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x863, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_BASIC_READ_REG32    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x864, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_BASIC_WRITE_REG32   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x865, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define KMDF_BASIC_PING_VALUE 0x4b4d4446UL /* "KMDF" */
#define KMDF_BASIC_ID_VALUE   0x4b4d4446UL /* "KMDF" */

typedef struct _KMDF_BASIC_VERSION {
    USHORT Major;
    USHORT Minor;
    USHORT Patch;
    USHORT Build;
} KMDF_BASIC_VERSION, *PKMDF_BASIC_VERSION;

typedef struct _KMDF_BASIC_STATE {
    ULONG Prepared;
    ULONG Powered;
    ULONG HasMmio;
    ULONG MmioLength;
    ULONG IoctlCount;
} KMDF_BASIC_STATE, *PKMDF_BASIC_STATE;

typedef struct _KMDF_BASIC_REG32_REQUEST {
    ULONG Offset;
    ULONG Value;
} KMDF_BASIC_REG32_REQUEST, *PKMDF_BASIC_REG32_REQUEST;
