#pragma once

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <windows.h>
#endif

#define IOCTL_KMDF_IF_PING               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x880, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_IF_GET_CONFIG         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x881, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_IF_GET_INTERFACE_STRING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x882, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_IF_GET_GREETING       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x883, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_IF_SET_RUNTIME_VALUE  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x884, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_IF_GET_RUNTIME_VALUE  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x885, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KMDF_IF_ECHO               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x886, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define KMDF_IF_PING_VALUE 0x49464b4dUL /* "MKFI" little-endian marker */

#define KMDF_IF_INTERFACE_GUID_STRING L"{9A7B0B24-6E57-4C51-AD3C-6D9F5F0E0001}"

typedef struct _KMDF_IF_CONFIG {
    ULONG Prepared;
    ULONG Powered;
    ULONG InterfaceCreated;

    ULONG Answer;
    ULONG SeenByDriver;
    ULONG DeviceSeenByDriver;
    ULONG RuntimeValue;
    ULONG CustomPropertyValue;

    ULONG GreetingLengthBytes;
    ULONG InterfaceStringLengthBytes;
    ULONG IoctlCount;
} KMDF_IF_CONFIG, *PKMDF_IF_CONFIG;

typedef struct _KMDF_IF_DWORD_VALUE {
    ULONG Value;
} KMDF_IF_DWORD_VALUE, *PKMDF_IF_DWORD_VALUE;

typedef struct _KMDF_IF_STRING_OUT {
    USHORT LengthBytes;
    USHORT MaximumLengthBytes;
    WCHAR Buffer[260];
} KMDF_IF_STRING_OUT, *PKMDF_IF_STRING_OUT;
