#pragma once

#include <ntddk.h>

/*
 * METHOD_BUFFERED only.
 *
 * This is a PnP + Power version of PnpMmioInterruptTest.
 * It waits for IRP_MN_START_DEVICE to map/connect resources and handles
 * IRP_MJ_POWER D0/D3 transitions.
 */

#define IOCTL_POWERPNP_GET_ID                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x840, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POWERPNP_READ_REG32              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x841, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POWERPNP_WRITE_REG32             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x842, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POWERPNP_WRITE_CONTROL           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x843, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POWERPNP_WAIT_FOR_INTERRUPT      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x844, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POWERPNP_GET_INTERRUPT_COUNT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x845, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POWERPNP_CANCEL_WAIT             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x846, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POWERPNP_GET_POWER_STATE         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x847, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define POWERPNP_ID_VALUE 0x4d4d494fUL /* "MMIO" */

typedef struct _POWERPNP_REG32_REQUEST {
    ULONG Offset;
    ULONG Value;
} POWERPNP_REG32_REQUEST, *PPOWERPNP_REG32_REQUEST;

typedef struct _POWERPNP_POWER_STATE_OUT {
    ULONG Started;
    ULONG Powered;
    ULONG SystemPowerState;
    ULONG DevicePowerState;
} POWERPNP_POWER_STATE_OUT, *PPOWERPNP_POWER_STATE_OUT;
