#pragma once

#include <ntddk.h>

#define IOCTL_SURT_PING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SURT_ECHO CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SURT_GET_VERSION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SURT_PING_VALUE 0x53555254UL /* "SURT" */

typedef struct _SURT_TEST_VERSION {
    ULONG Major;
    ULONG Minor;
    ULONG Patch;
    ULONG Build;
} SURT_TEST_VERSION, *PSURT_TEST_VERSION;
